@D_WebApi_HostAddress = http://localhost:5210

### Login POST request
POST {{D_WebApi_HostAddress}}/login
Content-Type: application/json

{
  "userName": "initial.user@example.com",
  "password": "InitialP@ss1"
}


### Login POST request
GET {{D_WebApi_HostAddress}}/olympic-winners
Content-Type: application/json
